spring:
  cloud:
    azure:
      servicebus:
        connection-string: ${connection-string}
    stream:
      function:
        definition: function1; function2
      bindings:
        function1-in-0:
          destination: longduration # lock duration is 5 minutes, represent for create-replica
        function1-out-0:
          destination: longduration-topic
        function2-in-0:
          destination: longduration2 # lock duration is 5 minutes, represent for destroy-replica
        function2-out-0:
          destination: longduration-topic
      servicebus:
        bindings:
          function1-in-0:
            consumer:
              entity-type: queue
              prefetch-count: 0
              max-concurrent-calls: 9
              max-auto-lock-renew-duration: 60M
          function1-out-0:
            producer:
              entity-type: topic
          function2-in-0:
            consumer:
              entity-type: queue
              prefetch-count: 0
              max-concurrent-calls: 9
              max-auto-lock-renew-duration: 60M
          function2-out-0:
            producer:
              entity-type: topic
